<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Casad_1</name>
   <tag></tag>
   <elementGuidId>d466753e-bd19-4768-a09d-679e9122de33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MA-Casad@']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54853ad4-fd78-41ab-b918-83586b6de6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MA-Casad@</value>
      <webElementGuid>97a63b39-451a-4041-8b66-e04b2147c232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>muscle-select-option clickable muscle-select-selected-option text-white</value>
      <webElementGuid>5c753e49-e42b-4c15-96f7-d5f8f40a7e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c834f010-dbca-4029-8002-ac24863a4701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Casad@</value>
      <webElementGuid>e42012f4-4cd4-44b1-aaa8-d41368ff7c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MA-Casad@&quot;)</value>
      <webElementGuid>76c56516-efb7-4efb-97ae-6b36326120e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='MA-Casad@']</value>
      <webElementGuid>18a949f0-afc2-4762-839c-5ce0367be1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='muscle-select-options']/div</value>
      <webElementGuid>065fceab-3d15-4ae3-84d1-3033d710b179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casad@'])[1]/following::div[5]</value>
      <webElementGuid>2ef9b992-0c7e-475a-8727-68a52fc26cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado civil *'])[1]/following::div[8]</value>
      <webElementGuid>5dbd4191-96c2-4f48-988f-42e5c7a05ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Viud@'])[1]/preceding::div[1]</value>
      <webElementGuid>7847e722-31f3-4b39-93b2-435881d57fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Separad@'])[1]/preceding::div[2]</value>
      <webElementGuid>4ccb85d4-1cbc-4472-9063-167104187bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>f8a4eab6-0fb9-48d6-b316-ae7427be0d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'MA-Casad@' and (text() = 'Casad@' or . = 'Casad@')]</value>
      <webElementGuid>0aa2598f-3d5c-4d72-829e-9c10cb28bc61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
