<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Descubre nuestras recomendaciones para _d34453_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>b9ce44e8-25ab-465c-869a-c1152dc7be9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div[2]/div[3]/div/div/div[2]/div/div/div[8]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>609e38ea-7698-48e7-ae04-ddeb87ebddd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://a.storyblok.com/f/290560/500x400/9df7487cd6/antigua.webp</value>
      <webElementGuid>7d7dd6ae-b6c3-4fe4-bb51-29113973fe80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Antigua</value>
      <webElementGuid>ff66daec-b6f7-49ce-b0e0-d635c35470ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-5/6 object-cover</value>
      <webElementGuid>9a964cb1-ec83-4ae9-ac56-4e1cdb360b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home-screen relative&quot;]/div[@class=&quot;home-screen-content global-page global-responsive-horizontal-paddings&quot;]/div[1]/div[@class=&quot;see-more-section&quot;]/div[@class=&quot;home-recommendations-content&quot;]/div[@class=&quot;container mx-auto&quot;]/div[@class=&quot;grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6&quot;]/div[@class=&quot;relative bg-white transition-transform transform hover:scale-105 cursor-pointer&quot;]/img[@class=&quot;w-full h-5/6 object-cover&quot;]</value>
      <webElementGuid>0f9ac0ec-881c-4871-9a87-ab1ce722cce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div[3]/div/div/div[2]/div/div/div[8]/img</value>
      <webElementGuid>f162a7bf-410a-4bf5-94e1-9ffccdc3f6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Antigua']</value>
      <webElementGuid>b499c078-1f5a-4abf-bcc4-670acc2519f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/img</value>
      <webElementGuid>9fe27355-0fc4-4965-a049-5bc58c451b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://a.storyblok.com/f/290560/500x400/9df7487cd6/antigua.webp' and @alt = 'Antigua']</value>
      <webElementGuid>875b1754-8e0f-4f69-b80d-fc7c59d2560f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
