<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Volver (1)</name>
   <tag></tag>
   <elementGuidId>977cd454-b2bc-4797-bb37-89821936135a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/div[2]/div/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.muscle-button.btn-type-link.text-base.tx-pmd-semiBold.tx-plg-bold.btn-size-small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23517d4c-50e3-45d2-b413-e7d0cd3a0c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>muscle-button btn-type-link text-base tx-pmd-semiBold tx-plg-bold btn-size-small</value>
      <webElementGuid>0b2018ee-b7c6-4241-919a-5e778b8dec73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Volver</value>
      <webElementGuid>f659f5b6-c909-47ce-9d6a-3efd7e014246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[@class=&quot;w-full flex flex-1 justify-center&quot;]/div[@class=&quot;w-full max-width-component&quot;]/div[@class=&quot;global-page global-responsive-horizontal-paddings mb-0 pb-0&quot;]/div[@class=&quot;mb-[27px]&quot;]/div[@class=&quot;mt-4&quot;]/button[@class=&quot;muscle-button btn-type-link text-base tx-pmd-semiBold tx-plg-bold btn-size-small&quot;]</value>
      <webElementGuid>449fba19-7ac6-4463-bb9b-7f86d5247098</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>50ce7e77-aacb-4998-8d4c-11d27c428246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrarse'])[1]/following::button[1]</value>
      <webElementGuid>6b446c55-e892-4cab-93ef-2c34abf35382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar sesión'])[1]/following::button[2]</value>
      <webElementGuid>60d2ed04-1d6b-4756-a982-193ed160a48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sheraton Orlando Lake Buena Vista Resort'])[1]/preceding::button[1]</value>
      <webElementGuid>3d849a32-abdd-4c59-b372-f4197fc27b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotel'])[1]/preceding::button[1]</value>
      <webElementGuid>a79dfea4-6d73-4c02-a59e-8769ccfc4b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Volver']/parent::*</value>
      <webElementGuid>5dd52a66-c037-47cc-9b82-637c91f8ce90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>c1ea944e-65d2-44a4-a1b8-31816932dda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Volver' or . = 'Volver')]</value>
      <webElementGuid>92eb572e-2598-4f05-8a18-93f815295dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
