<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fb146acc-b68b-4c98-a99a-2c458b15c607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Platform Logo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9991d3c1-a7fb-45e8-9860-52d76aaf9df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Platform Logo</value>
      <webElementGuid>11000240-feff-462b-9e0f-18efd7bde0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>f4ed6604-5efd-439b-b8aa-20b76bcd71c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>32cf2030-d83f-4e06-ab7b-9c38f14b3a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>e169ce90-94db-4061-a32b-c04c31ee1385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>7d02c8fa-d73b-45ef-a42c-c798ec5624b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=640&amp;q=75 640w, /_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=750&amp;q=75 750w, /_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=828&amp;q=75 828w, /_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>8addb3bb-c134-448f-95e7-73b47d7cb707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=3840&amp;q=75</value>
      <webElementGuid>bd0d894d-1e13-4bc3-b5c8-95a2059e3b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[1]/div[@class=&quot;header headerDynamicStyle&quot;]/div[@class=&quot;header-content   !py-0 !w-full&quot;]/div[@class=&quot;header-element header-logo hidden md:block clickable w-fit -translate-x-3 lg:-translate-x-7&quot;]/div[@class=&quot;relative&quot;]/img[1]</value>
      <webElementGuid>1acc2da1-e215-41e4-b22e-d29527fbc6bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/div/div/div/div/img</value>
      <webElementGuid>fbabe2c6-c615-4bad-898e-6d369d640b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Platform Logo']</value>
      <webElementGuid>dc482ef9-d758-40fc-b114-f518d741d093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>652c4736-811c-4911-8d62-f99c9b7f6ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Platform Logo' and @src = '/_next/image?url=https%3A%2F%2Fa.storyblok.com%2Ff%2F290560%2F170x62%2Fa6ced998b2%2Fshopstar-viajes.png&amp;w=3840&amp;q=75']</value>
      <webElementGuid>786a50c9-5eea-40c1-9cf7-f983c6cec9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
