<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Autos_outlined-read-only-input</name>
   <tag></tag>
   <elementGuidId>b280a713-8fab-4a10-b09d-5de3325df673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outlined-read-only-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outlined-read-only-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35c14494-0e35-4ca0-b748-24bdfcbdee83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>01614f87-e937-422c-81e7-ab1e1fee1908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-read-only-input</value>
      <webElementGuid>1d95957c-bf1d-4628-a1c8-c7111bbfcfbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input Mui-readOnly MuiInputBase-readOnly css-1pog434</value>
      <webElementGuid>f0384213-861f-43e4-98d2-8616f6e3e940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc53caf8-6d67-4685-9af2-36a8c9bab073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> 22 Ago, 2024 / 22 Ago, 2024</value>
      <webElementGuid>709b10ae-60b6-474c-b0b8-bb2652f22f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outlined-read-only-input&quot;)</value>
      <webElementGuid>0a4e4b95-cabe-49c3-bc0a-469bbb46e552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outlined-read-only-input']</value>
      <webElementGuid>7c2e67a7-ee07-4e46-9e37-0ac30899dd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>c5c2b945-9c07-4363-9664-f9c242b33363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>d59939e4-9bdb-4ad9-8854-470ce47702ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-read-only-input' and @type = 'text']</value>
      <webElementGuid>f834de4b-6863-4f7c-94b0-dbb0f7431746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
