<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_do_w-full</name>
   <tag></tag>
   <elementGuidId>f8a1a3cd-0b18-4171-a234-db6e72744e89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[3]/div/div[2]/div[1]/div/div[1]/div/div[2]/div[1]/div/div[2]/div/div/div/div[2]/div[1]/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>374b88aa-3b86-45ef-b4ec-9ec14815d816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full</value>
      <webElementGuid>dc24fdd3-ff69-4990-84d8-d78e1153c97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>e2e45b78-1118-4211-9ea0-7adf3451e117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>27/08/2024</value>
      <webElementGuid>bd988672-b374-4368-aa5f-d6189b8fa346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;global-page global-responsive-horizontal-paddings&quot;]/div[@class=&quot;flex flex-row gap-12 pt-4 flex-wrap h-full&quot;]/div[@class=&quot;products-search-content flex-1 w-full flex flex-col gap-4&quot;]/div[@class=&quot;hidden md:flex w-full&quot;]/div[@class=&quot;flex flex-col w-full gap-3&quot;]/div[@class=&quot;flex flex-col xl:flex-row  items-end w-full gap-3&quot;]/div[@class=&quot;flex flex-col gap-3 w-full&quot;]/div[@class=&quot;flex w-full flex-wrap gap-3 flex-col md:flex-row&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/div[@class=&quot;relative h-0 z-[500]&quot;]/div[@class=&quot;absolute z-10 mt-0 top-1 min-w-fit rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none left-0 w-fit&quot;]/div[@class=&quot;py-1&quot;]/div[@class=&quot;flex flex-col p-4 w-min&quot;]/div[@class=&quot;flex flex-col w-full justify-between md:flex-row&quot;]/div[@class=&quot;flex-1 pt-[1em] flex flex-row items-center gap-2 w-full md:border-r md:border-neutral-300 md:pr-[1em]&quot;]/div[@class=&quot;global-input w-full text-2xs md:text-xs text-black&quot;]/div[@class=&quot;global-input-box flex flex-row items-center&quot;]/input[@class=&quot;w-full&quot;]</value>
      <webElementGuid>f8fc6e36-b299-4eef-911f-fee404870b39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='27/08/2024']</value>
      <webElementGuid>e3763f28-7432-4e4e-8998-658c33a4198d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[3]/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>fc42f011-a25b-418f-a0af-1f31826689d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>0670e480-9ada-4cec-beb7-f39a87230acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>9ced17b3-51ce-4fde-8ee4-3d0de0b00230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
