<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Listo</name>
   <tag></tag>
   <elementGuidId>3acdbc3b-b271-4e63-9067-10317846ffe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.muscle-button.btn-type-solid.btn-size-full-length.text-base.bold-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[2]/div[2]/div/div[2]/div/div[1]/div/div[2]/div/div/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>194c7920-c9d1-4cc1-9819-5c7332850f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>muscle-button btn-type-solid btn-size-full-length text-base bold-text</value>
      <webElementGuid>47482338-6eb0-4a77-abce-479623c53129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Listo</value>
      <webElementGuid>7eaa95de-7c1d-42c3-8c76-4236cfc07316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home-screen relative&quot;]/div[@class=&quot;nav-card-container global-responsive-horizontal-paddings&quot;]/div[@class=&quot;nav-card&quot;]/div[@class=&quot;nav-card-section&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-row w-full&quot;]/div[@class=&quot;flex flex-col relative&quot;]/div[@class=&quot;relative w-full&quot;]/div[@class=&quot;absolute z-10 mt-0 min-w-fit bg-white rounded-md shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none left-0 w-fit max-w-full&quot;]/div[@class=&quot;py-1&quot;]/div[@class=&quot;flex flex-col gap-4 p-4 w-72&quot;]/button[@class=&quot;muscle-button btn-type-solid btn-size-full-length text-base bold-text&quot;]</value>
      <webElementGuid>e3a40bbc-39b7-4b7f-aace-d0664bc6846e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/button[2]</value>
      <webElementGuid>2d0e5888-0c0e-478f-beed-63c2ee20ba52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Añadir habitación'])[1]/following::button[1]</value>
      <webElementGuid>1fe46e19-81be-46f5-a237-872b434e8196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[4]/following::button[2]</value>
      <webElementGuid>7168b9ca-973c-44a9-841e-0165c5bc5016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/preceding::button[2]</value>
      <webElementGuid>f5bc5c6a-bfb7-4b3a-8008-7ebb20ecc39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descubre nuestras recomendaciones para ti'])[1]/preceding::button[3]</value>
      <webElementGuid>5494286d-1fc8-4bf1-88c2-56c7d095cebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Listo']/parent::*</value>
      <webElementGuid>0165be7f-9ecd-4101-b3fb-baead46fe7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button[2]</value>
      <webElementGuid>f1e3dff0-5da0-4299-8ba2-3e1b665551c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Listo' or . = 'Listo')]</value>
      <webElementGuid>9445df94-55da-4716-9c1d-119ca1917d9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
