<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Recomendado_w-full h-full object-cover _de3e67</name>
   <tag></tag>
   <elementGuidId>d4adcecd-0548-416f-b6c3-bfad02bfe1bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div[2]/div/div[2]/div[3]/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-full.h-full.object-cover.border-none</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a29e8b4d-5471-4f77-9e89-f2c0d22b7280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hilton Garden Inn San Jose La Sabana</value>
      <webElementGuid>1eeef7d4-aa1a-4a84-b259-9aa03ada5a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.travelapi.com/lodging/11000000/10580000/10579900/10579877/7651c4f5_z.jpg</value>
      <webElementGuid>ca5e0f1e-410c-4772-9a18-6539f16ff7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-full object-cover border-none</value>
      <webElementGuid>0d212504-5fe9-49f2-94fa-1bf1abdd0a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;global-page global-responsive-horizontal-paddings&quot;]/div[@class=&quot;flex flex-row gap-8&quot;]/div[@class=&quot;flex-1 flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col gap-4 w-full h-fit&quot;]/div[@class=&quot;flex flex-col lg:flex-row lg:items-center lg:flex-wrap gap-8 w-full overflow-hidden global-card pb-3 md:pb-0 relative&quot;]/div[@class=&quot;w-full flex-1 max-lg:max-h-[375px] h-full&quot;]/img[@class=&quot;w-full h-full object-cover border-none&quot;]</value>
      <webElementGuid>d595d849-60d3-455b-a38d-7b6c9f77b211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div/div[2]/div[3]/div[2]/div[2]/img</value>
      <webElementGuid>390e3c91-86ad-4fbb-a889-be1a109dbbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hilton Garden Inn San Jose La Sabana']</value>
      <webElementGuid>025d25f9-73d2-46d5-b977-b02fa518ee9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/img</value>
      <webElementGuid>a702c2cf-5179-4237-8287-c3475cab4a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Hilton Garden Inn San Jose La Sabana' and @src = 'https://i.travelapi.com/lodging/11000000/10580000/10579900/10579877/7651c4f5_z.jpg']</value>
      <webElementGuid>6dd68fde-7951-41ff-950f-9f60165d3604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
