<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Autos_outlined-read-only-input</name>
   <tag></tag>
   <elementGuidId>8993b46b-6cf9-46af-a03b-77a857fd04d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outlined-read-only-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;outlined-read-only-input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3168cd2-c180-4c4d-97c6-ce2d53617394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd34ecc8-f756-47db-9a58-c2665f3a348d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-read-only-input</value>
      <webElementGuid>4b4332c4-4ddb-4c0b-b85c-1da2169ebb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input Mui-readOnly MuiInputBase-readOnly css-1pog434</value>
      <webElementGuid>3d46b754-aa5f-4392-a177-9346e9579c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c46056e7-3604-4e06-823e-30839ad0b55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value> Sáb, 10 Ago, 2024 / Jue, 15 Ago, 2024</value>
      <webElementGuid>d2c2bb80-7493-444f-83b5-b9a9dd4e01a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outlined-read-only-input&quot;)</value>
      <webElementGuid>2b62dc51-2792-46cd-925c-fefbc4212016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outlined-read-only-input']</value>
      <webElementGuid>508ef2e7-c0e4-4517-aab4-b7b022cdb9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>c1aa8cd3-c44d-47eb-9540-0e51f67866f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>ef6db7c9-659f-4b7c-a23d-3d0fe23e3e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-read-only-input' and @type = 'text']</value>
      <webElementGuid>b909f477-f7fa-4f39-9cb9-ac90fb9b7395</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
