<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_do_w-full - 2nd</name>
   <tag></tag>
   <elementGuidId>504a40e6-62a1-4aca-8369-b63ab7b0727f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[1]/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9790b0c8-b8ab-4b48-b081-a1616df3b43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full</value>
      <webElementGuid>617c86cb-246a-4232-82a2-37bcde6a27f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>0f6a6434-0a23-4ae0-845f-3c9de6317856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10/08/2024</value>
      <webElementGuid>c05ee885-0268-471b-848e-bf580cc5def0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home-screen relative&quot;]/div[@class=&quot;nav-card-container global-responsive-horizontal-paddings&quot;]/div[@class=&quot;nav-card&quot;]/div[@class=&quot;nav-card-section&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col md:flex-row md:items-center gap-4&quot;]/div[@class=&quot;flex flex-col w-full flex-1&quot;]/div[@class=&quot;relative h-0 z-[500]&quot;]/div[@class=&quot;absolute z-10 mt-0 top-1 min-w-fit rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none right-0 w-fit&quot;]/div[@class=&quot;py-1&quot;]/div[@class=&quot;flex flex-col p-4 w-min&quot;]/div[@class=&quot;flex flex-col w-full justify-between md:flex-row&quot;]/div[@class=&quot;flex-1 pt-[1em] flex flex-row items-center gap-2 w-full md:border-r md:border-neutral-300 md:pr-[1em]&quot;]/div[@class=&quot;global-input w-full text-2xs md:text-xs text-black&quot;]/div[@class=&quot;global-input-box flex flex-row items-center&quot;]/input[@class=&quot;w-full&quot;]</value>
      <webElementGuid>33175f53-db15-4edf-afaf-a60641c80cda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='10/08/2024']</value>
      <webElementGuid>018609e5-f559-48c1-a9b8-f4d6a2d688a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>86063d1a-c073-4a02-a726-c515799403a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>eb405314-317a-4a41-905c-f75224e91c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>30406f78-40e7-4110-bbf1-e34e03497ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
