<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_do_w-full</name>
   <tag></tag>
   <elementGuidId>26e6c090-7758-475b-8418-595f65aa9873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.w-full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[1]/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04063bc1-ec3b-4bb9-a7e1-b142daca011f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full</value>
      <webElementGuid>50f7c001-8f52-439b-8e00-7affdc941b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>2e4def2b-fb52-4936-bc37-7994fb9b2e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10/08/2024</value>
      <webElementGuid>c0ed3e39-3ee0-43e4-a9dd-0e32fcda1c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home-screen relative&quot;]/div[@class=&quot;nav-card-container global-responsive-horizontal-paddings&quot;]/div[@class=&quot;nav-card&quot;]/div[@class=&quot;nav-card-section&quot;]/div[@class=&quot;flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col md:flex-row md:items-center gap-4&quot;]/div[@class=&quot;flex flex-col w-full flex-1&quot;]/div[@class=&quot;relative h-0 z-[500]&quot;]/div[@class=&quot;absolute z-10 mt-0 top-1 min-w-fit rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none right-0 w-fit&quot;]/div[@class=&quot;py-1&quot;]/div[@class=&quot;flex flex-col p-4 w-min&quot;]/div[@class=&quot;flex flex-col w-full justify-between md:flex-row&quot;]/div[@class=&quot;flex-1 pt-[1em] flex flex-row items-center gap-2 w-full md:border-r md:border-neutral-300 md:pr-[1em]&quot;]/div[@class=&quot;global-input w-full text-2xs md:text-xs text-black&quot;]/div[@class=&quot;global-input-box flex flex-row items-center&quot;]/input[@class=&quot;w-full&quot;]</value>
      <webElementGuid>85168e1e-3fd7-4492-8657-f08199921a9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='10/08/2024']</value>
      <webElementGuid>1b11ff4f-d843-4258-a777-1e8f892c73ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>6b368716-92ac-4f9b-b1e5-857b8895d472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>b4caa9ca-d143-4ab5-a7e6-f037f588a4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>744c744e-0389-46b8-a488-f71b027cf207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
