<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_San Jos, Provincia de San Jos, Costa Rica</name>
   <tag></tag>
   <elementGuidId>20b27faf-ed8a-4176-8d09-3d8e2d7529fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='hotels-destination-autocomplete-option-0']/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.font-bold.text-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ac6bf86b-106e-476a-a390-6d410b99117b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-bold text-sm</value>
      <webElementGuid>17a17904-8c39-43b2-99e5-afc53a22feba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>San José, Provincia de San José, Costa Rica</value>
      <webElementGuid>91899462-74a3-42ba-9330-7635a6ae8bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hotels-destination-autocomplete-option-0&quot;)/div[@class=&quot;flex items-center p-2&quot;]/div[2]/p[@class=&quot;font-bold text-sm&quot;]</value>
      <webElementGuid>1f698138-bfca-4878-a0c3-90916ce11e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='hotels-destination-autocomplete-option-0']/div/div[2]/p</value>
      <webElementGuid>a901a252-08a0-4d2f-854c-780e85f76100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Métodos de pago:'])[1]/following::p[1]</value>
      <webElementGuid>5f0dec05-cffe-470f-b84a-8e6d91b31394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos y condiciones'])[1]/following::p[1]</value>
      <webElementGuid>b26826cc-9cc4-4404-8595-5731550dcda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='San José, Provincia de San José, Costa Rica']/parent::*</value>
      <webElementGuid>12d366d8-48e8-4e4f-9456-b0ff49ce2d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[2]/p</value>
      <webElementGuid>eb9505b5-49d0-4816-81db-5b885fe764f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'San José, Provincia de San José, Costa Rica' or . = 'San José, Provincia de San José, Costa Rica')]</value>
      <webElementGuid>c0e69e5e-0b21-4bf6-b992-abf469b10a47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
