<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ingresar</name>
   <tag></tag>
   <elementGuidId>8536dc75-b4ea-4cae-a651-787e20e641bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ibk-button.ibk-button--primary.ibk-button--medium.ibk-button--green.ibk-button--full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9b8d67a-062e-45b5-a5b8-8503d2c47eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibk-button ibk-button--primary ibk-button--medium ibk-button--green ibk-button--full</value>
      <webElementGuid>c8eb8e15-3c0f-4400-9d3f-e52e92e7a1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dc4c1ba6-5995-4372-9f45-09c18719cb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>5c306e7f-b748-4e6d-863d-7c61c1f249be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/ibk-form[@class=&quot;login__form hydrated&quot;]/form[@class=&quot;ibk-form&quot;]/ibk-button[@class=&quot;hydrated&quot;]/button[@class=&quot;ibk-button ibk-button--primary ibk-button--medium ibk-button--green ibk-button--full&quot;]</value>
      <webElementGuid>21d60cdb-845a-4fe0-ae81-9a2dfbe9f6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Explore/Login User/Page_Explore/iframe_Cancelar_authentication-iframe</value>
      <webElementGuid>d6c05d42-4082-4bb0-abc8-f40cc7d98456</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>25db243e-d2ed-4530-b261-04a042da2022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/ibk-form/form/ibk-button/button</value>
      <webElementGuid>1005a327-2010-4f3d-a217-465ba1adc622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Olvidaste tu contraseña?'])[1]/following::button[1]</value>
      <webElementGuid>76727694-615f-4c01-8adb-3411982f9166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pasaporte'])[1]/following::button[1]</value>
      <webElementGuid>94dc380b-8b4d-46bc-801b-dbddd385798a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crea tu cuenta'])[1]/preceding::button[1]</value>
      <webElementGuid>87d4bccb-5e1e-420c-bffb-afbfa9529e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2fc2aad2-9484-4a18-8973-3fb7ac5a3c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Ingresar' or . = 'Ingresar')]</value>
      <webElementGuid>114494fd-f49f-465c-bb22-052a20884994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
