<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_enviar_codigo</name>
   <tag></tag>
   <elementGuidId>8e0adca2-b808-4a2e-a456-a38e592a5595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ibk-button.ibk-button--primary.ibk-button--medium.ibk-button--green.ibk-button--full</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;otp&quot;]/ibk-button/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6cfb4b72-db9e-4687-b844-436b46a498bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibk-button ibk-button--primary ibk-button--medium ibk-button--green ibk-button--full</value>
      <webElementGuid>fb57ec2c-cf63-4c98-aa45-7ccc08a0254a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a7dbdabd-8e54-4c3a-bb39-da6b24aab075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ingresar</value>
      <webElementGuid>b4e6ea33-b3cf-4812-8885-d1d57ac26a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/ibk-form[@class=&quot;login__form hydrated&quot;]/form[@class=&quot;ibk-form&quot;]/ibk-button[@class=&quot;hydrated&quot;]/button[@class=&quot;ibk-button ibk-button--primary ibk-button--medium ibk-button--green ibk-button--full&quot;]</value>
      <webElementGuid>8a804244-d7e4-44da-a9fe-f13dbcabc0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Explore/Login User/Page_Explore/iframe_Cancelar_authentication-iframe</value>
      <webElementGuid>61a9796b-b453-4b97-a2d3-9269f877e085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>4342de77-88cc-4e7e-84d5-55ae8ae2767c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/ibk-form/form/ibk-button/button</value>
      <webElementGuid>8fb0e8de-c720-4abb-b276-4074c139c7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Olvidaste tu contraseña?'])[1]/following::button[1]</value>
      <webElementGuid>cf05d540-79ce-484a-9e26-e1141ca8de78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pasaporte'])[1]/following::button[1]</value>
      <webElementGuid>44ca256c-ac9c-4076-bfc9-e8e046f29cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crea tu cuenta'])[1]/preceding::button[1]</value>
      <webElementGuid>1b7b4b1a-3ad9-496f-8989-0b06e9b72213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5ece21c4-f792-4c3d-b335-7aee8c58e708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Ingresar' or . = 'Ingresar')]</value>
      <webElementGuid>ba776c75-0e08-4a0a-a1a4-2482924beb3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
