<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Olvidaste tu contrasea_a-6buan8uzynah</name>
   <tag></tag>
   <elementGuidId>0a26f6b6-6812-4c70-b2e3-15435ff8f53b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-6buan8uzynah&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-6buan8uzynah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a19c283e-c827-42fd-910c-f28d3f7ef92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>3a73a41b-5d33-4175-b800-2435136bdc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>83fc2afc-8da6-49be-af56-b2ed389d4658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>d155abab-b12e-48e0-84f2-9d54b43acbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>331da18d-930f-42df-b421-facd08f45401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-6buan8uzynah</value>
      <webElementGuid>405a038a-5e1e-40c6-8409-7335c90c93ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e36fea5-20ca-4228-8509-44218c2e4c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2ff1afab-231d-48e6-8dd2-beeb36eff6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>8d07cb57-8294-4388-8f45-1e46cec20cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lcg7VUUAAAAAMC2kjpbF7ctov3SAHufCwFr7oxI&amp;co=aHR0cHM6Ly9hdXRoaW50ZXJiYW5rYmVuZWZpdC5henVyZWVkZ2UubmV0OjQ0Mw..&amp;hl=es-419&amp;v=rKbTvxTxwcw5VqzrtN-ICwWt&amp;size=normal&amp;cb=eh2c4287d10s</value>
      <webElementGuid>a7750b09-f78e-42df-8b8a-9eeab0472408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngrecaptcha-0&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>b2012a41-76cd-43f7-adc7-1243abe462db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Explore/Login User/Page_Explore/iframe_Cancelar_authentication-iframe-captcha</value>
      <webElementGuid>f707fc06-e5ce-4a07-b79f-ceea97774bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-6buan8uzynah']</value>
      <webElementGuid>33257224-17bf-42c3-a2fe-c1d0f692a255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//re-captcha[@id='ngrecaptcha-0']/div/div/iframe</value>
      <webElementGuid>f296a852-16f7-4e2b-8c62-d4492a1beddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>530c6f32-dbbe-4d3b-8c81-1a34b67b7a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-6buan8uzynah' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lcg7VUUAAAAAMC2kjpbF7ctov3SAHufCwFr7oxI&amp;co=aHR0cHM6Ly9hdXRoaW50ZXJiYW5rYmVuZWZpdC5henVyZWVkZ2UubmV0OjQ0Mw..&amp;hl=es-419&amp;v=rKbTvxTxwcw5VqzrtN-ICwWt&amp;size=normal&amp;cb=eh2c4287d10s']</value>
      <webElementGuid>d3ba6e23-78a9-48ba-8c1e-ac90da397a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
