<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cancelar_authentication-iframe</name>
   <tag></tag>
   <elementGuidId>285b5335-849e-4dab-ab96-b2f12faee29d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iframe-auth-modal']/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.authentication-iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>35f2c90f-f9ba-415b-b2df-94e5cbb4bccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>callback_url</name>
      <type>Main</type>
      <value>https://exploremuscle.com/customer_users/auth/benefit/callback</value>
      <webElementGuid>8272819a-bf8c-4f27-8ca5-63da55680203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authentication-iframe</value>
      <webElementGuid>d55260b0-2274-4628-b7a3-ce74cda1921f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>cebcaab3-314e-41ac-8951-9b79ea0e10f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://authinterbankbenefit.azureedge.net/auth/authorize/v1/index.html?client_id=MUSCLE&amp;redirect_uri=https%3A%2F%2Fexploremuscle.com%2Fcustomer_users%2Fauth%2Fbenefit%2Fcallback&amp;response_mode=web_message&amp;scope=login&amp;token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJncmFudF90eXBlIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwic2NvcGUiOlsicmVhZCJdLCJpZF9vYXV0aF9jbGllbnQiOjI4LCJyZWRpcmVjdF91cmkiOm51bGwsImV4cCI6MTcyMTMyNDU0OCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9UUlVTVEVEX0NMSUVOVCJdLCJqdGkiOiJpQ2dfWmpUakxnYUQ5c1FUWWgwX0lia0NvV1UiLCJjbGllbnRfaWQiOiJNVVNDTEUifQ.wxHYp6CmRW3Wd38kDoGc0BjAhekCjbJFF_lqFbyckR4</value>
      <webElementGuid>48ac0146-344e-47bf-bd7c-bbb224aee7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe-auth-modal&quot;)/div[@class=&quot;modal-dialog iframe-auth-dialog modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content h-100 rounded-0&quot;]/iframe[@class=&quot;authentication-iframe&quot;]</value>
      <webElementGuid>b9deb86a-45f0-49ab-82c8-025d011b3225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframe-auth-modal']/div/div/iframe</value>
      <webElementGuid>57eaedaa-8860-44ed-8d5e-1aa753fe38bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7be32b92-c960-4b19-ad03-b5a7e7f30961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://authinterbankbenefit.azureedge.net/auth/authorize/v1/index.html?client_id=MUSCLE&amp;redirect_uri=https%3A%2F%2Fexploremuscle.com%2Fcustomer_users%2Fauth%2Fbenefit%2Fcallback&amp;response_mode=web_message&amp;scope=login&amp;token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJncmFudF90eXBlIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwic2NvcGUiOlsicmVhZCJdLCJpZF9vYXV0aF9jbGllbnQiOjI4LCJyZWRpcmVjdF91cmkiOm51bGwsImV4cCI6MTcyMTMyNDU0OCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9UUlVTVEVEX0NMSUVOVCJdLCJqdGkiOiJpQ2dfWmpUakxnYUQ5c1FUWWgwX0lia0NvV1UiLCJjbGllbnRfaWQiOiJNVVNDTEUifQ.wxHYp6CmRW3Wd38kDoGc0BjAhekCjbJFF_lqFbyckR4']</value>
      <webElementGuid>2b36bed0-4f19-4e49-b73b-6921975ffac9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
