<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cancelar_authentication-iframe-captcha</name>
   <tag></tag>
   <elementGuidId>ea54876e-d941-4583-be50-3d51035dff84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.authentication-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iframe-auth-modal']/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>14663fda-da32-424e-b285-e689f92713d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>callback_url</name>
      <type>Main</type>
      <value>https://exploremuscle.com/customer_users/auth/benefit/callback</value>
      <webElementGuid>fae19717-1c1a-4c63-b2c7-2304897052c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>authentication-iframe</value>
      <webElementGuid>5b54e323-74af-4d42-8f60-d625e9f91319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>31818eb9-ef04-4a62-872a-b218ed0e5c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://authinterbankbenefit.azureedge.net/auth/authorize/v1/index.html?client_id=MUSCLE&amp;redirect_uri=https%3A%2F%2Fexploremuscle.com%2Fcustomer_users%2Fauth%2Fbenefit%2Fcallback&amp;response_mode=web_message&amp;scope=login&amp;token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJncmFudF90eXBlIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwic2NvcGUiOlsicmVhZCJdLCJpZF9vYXV0aF9jbGllbnQiOjI4LCJyZWRpcmVjdF91cmkiOm51bGwsImV4cCI6MTcyMTY3OTE3NCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9UUlVTVEVEX0NMSUVOVCJdLCJqdGkiOiJXa0tHMndtTURTU21RRkdTTE9iVnp2aXJELXciLCJjbGllbnRfaWQiOiJNVVNDTEUifQ.I_69-uQu1lBNOBstxyYJcZ2prpPpTkR-mxu0JsMIZyI</value>
      <webElementGuid>dffeb85d-e894-457f-bc77-5750d080d6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iframe-auth-modal&quot;)/div[@class=&quot;modal-dialog iframe-auth-dialog modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content h-100 rounded-0&quot;]/iframe[@class=&quot;authentication-iframe&quot;]</value>
      <webElementGuid>b228fe33-31a6-4195-81c4-758c61e9e181</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iframe-auth-modal']/div/div/iframe</value>
      <webElementGuid>b639d3c3-fb07-4acc-9380-c434378a7876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a1a1f99b-449c-473f-bd67-2a5758a01744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://authinterbankbenefit.azureedge.net/auth/authorize/v1/index.html?client_id=MUSCLE&amp;redirect_uri=https%3A%2F%2Fexploremuscle.com%2Fcustomer_users%2Fauth%2Fbenefit%2Fcallback&amp;response_mode=web_message&amp;scope=login&amp;token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJncmFudF90eXBlIjoiY2xpZW50X2NyZWRlbnRpYWxzIiwic2NvcGUiOlsicmVhZCJdLCJpZF9vYXV0aF9jbGllbnQiOjI4LCJyZWRpcmVjdF91cmkiOm51bGwsImV4cCI6MTcyMTY3OTE3NCwiYXV0aG9yaXRpZXMiOlsiUk9MRV9UUlVTVEVEX0NMSUVOVCJdLCJqdGkiOiJXa0tHMndtTURTU21RRkdTTE9iVnp2aXJELXciLCJjbGllbnRfaWQiOiJNVVNDTEUifQ.I_69-uQu1lBNOBstxyYJcZ2prpPpTkR-mxu0JsMIZyI']</value>
      <webElementGuid>83e6d104-0a47-4378-afb0-90501dba9e13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
