<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pass_ibk-textfield__value_1</name>
   <tag></tag>
   <elementGuidId>e60a6375-7ccb-4e46-b931-48eee546911c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ibk-textfield.ibk-textfield--password.ibk-textfield--focus > label.ibk-textfield__input > input.ibk-textfield__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7c8fd39-954b-4452-b14d-0cad9281418b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibk-textfield__value</value>
      <webElementGuid>d5f404cb-2bce-4217-8ac2-2814b976d822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9616ebb9-9a5c-42e7-b8b8-eedb52c0abc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>e9cfce22-30e5-4771-922f-36bda0c1257c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>cd404f87-e992-4ed7-b134-8cb0a3d6b91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/ibk-form[@class=&quot;login__form hydrated&quot;]/form[@class=&quot;ibk-form&quot;]/ibk-textfield[@class=&quot;login__password hydrated&quot;]/div[@class=&quot;ibk-textfield ibk-textfield--password ibk-textfield--focus&quot;]/label[@class=&quot;ibk-textfield__input&quot;]/input[@class=&quot;ibk-textfield__value&quot;]</value>
      <webElementGuid>36e8f301-2033-4da9-addd-d6cc20d74ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Explore/Login User/Page_Explore/iframe_Cancelar_authentication-iframe</value>
      <webElementGuid>b7f83dfd-d1b3-43b5-9773-93dc238cd5f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>34401746-4db8-40f5-b6ef-0d7b9b6d68f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/ibk-form/form/ibk-textfield/div/label/input</value>
      <webElementGuid>a3c869b4-634b-41f6-ac37-b6b8a6198ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ibk-textfield/div/label/input</value>
      <webElementGuid>06d054fb-e731-40d5-aaf5-3d9656bf7b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Contraseña']</value>
      <webElementGuid>72843c9d-7462-44b9-9f2d-62447717d817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
