<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email_ibk-textfield__value_1</name>
   <tag></tag>
   <elementGuidId>bc11f014-f87b-4190-9375-7c4f3d18cde6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ibk-textfield.ibk-textfield--password.ibk-textfield--focus > label.ibk-textfield__input > input.ibk-textfield__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;otp&quot;]/ibk-textfield/div/label/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c502782-67cf-4535-80f5-d6b62087518d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibk-textfield__value</value>
      <webElementGuid>e9afd441-3387-4905-a7ed-d3ea8f2a8819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c9376d15-269f-497b-96d2-b82d1e62ec8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>0483ebef-703a-4ea2-97b1-234200a3d7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b3c8aec9-9851-4a8d-be0e-ca18dcd8e216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/ibk-form[@class=&quot;login__form hydrated&quot;]/form[@class=&quot;ibk-form&quot;]/ibk-textfield[@class=&quot;login__password hydrated&quot;]/div[@class=&quot;ibk-textfield ibk-textfield--password ibk-textfield--focus&quot;]/label[@class=&quot;ibk-textfield__input&quot;]/input[@class=&quot;ibk-textfield__value&quot;]</value>
      <webElementGuid>0f14b568-18a6-43f2-a2bb-d8fa04cd0f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Explore/Login User/Page_Explore/iframe_Cancelar_authentication-iframe</value>
      <webElementGuid>8630d524-cdb2-4281-9e41-cb4431846c66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>5af23797-0875-4d0f-bace-e323c033734a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/ibk-form/form/ibk-textfield/div/label/input</value>
      <webElementGuid>2f487ad5-2b1f-4699-80b1-29994e5dd342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ibk-textfield/div/label/input</value>
      <webElementGuid>a9b1f7c7-6fd2-4595-849d-01828b3e786e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Contraseña']</value>
      <webElementGuid>bd3da392-2273-4cd5-a240-08be4617ae76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
