<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DNI_ibk-textfield__value</name>
   <tag></tag>
   <elementGuidId>8ecd21b2-ee92-4022-b985-2a43250f3efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ibk-textfield__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5fa9e9a-e60b-48cd-87d1-81b2b3341880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ibk-textfield__value</value>
      <webElementGuid>a52c1621-bda4-48b4-9524-21be28527bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f04f014-d840-4fb0-893a-3f6d9354108e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Número de documento</value>
      <webElementGuid>13e68b1e-1147-4c63-b62b-b32614878c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>f22e43db-6af0-49ad-830c-58a69b908ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/ibk-form[@class=&quot;login__form hydrated&quot;]/form[@class=&quot;ibk-form&quot;]/ibk-form-group[@class=&quot;login__form-group hydrated&quot;]/div[@class=&quot;ibk-form-group&quot;]/div[@class=&quot;ibk-form-group__list&quot;]/ibk-textfield[@class=&quot;login__document-number hydrated&quot;]/div[@class=&quot;ibk-textfield ibk-textfield--dni ibk-textfield--focus&quot;]/label[@class=&quot;ibk-textfield__input&quot;]/input[@class=&quot;ibk-textfield__value&quot;]</value>
      <webElementGuid>b71f81f1-d827-45ed-b0b5-3f4392f07227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Explore/Login User/Page_Explore/iframe_Cancelar_authentication-iframe</value>
      <webElementGuid>9604f235-0242-45b8-bf57-ae870cd67e8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>9caa84af-d0b3-4e3a-9ced-406b333409d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/ibk-form/form/ibk-form-group/div/div/ibk-textfield/div/label/input</value>
      <webElementGuid>c93ed7fe-4b54-415c-b7bf-df347d390c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ibk-textfield/div/label/input</value>
      <webElementGuid>39d3398f-826f-4c3a-8094-6b56c5d4f7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Número de documento']</value>
      <webElementGuid>e0a6475b-a12e-4b35-8555-b41d5e594adf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
