<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Hotel</name>
   <tag></tag>
   <elementGuidId>249d52b7-3700-4fc9-a83a-1c805bc35531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div[2]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>79028e69-29d1-460e-b11d-6cc0eecfd579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotel</value>
      <webElementGuid>a06c38dd-6ec8-4a7e-8511-d07c233c9be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;global-page global-responsive-horizontal-paddings&quot;]/div[@class=&quot;flex flex-row gap-8&quot;]/div[@class=&quot;hidden md:flex flex-col&quot;]/div[@class=&quot;flex flex-col gap-4 w-full&quot;]/div[@class=&quot;flex flex-col gap-2 min-w-[250px]&quot;]/div[@class=&quot;border-t border-neutral-100 w-full&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiAccordion-root MuiAccordion-rounded Mui-expanded MuiAccordion-gutters css-1jpy9ai&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-vertical MuiCollapse-entered css-c4sutr&quot;]/div[@class=&quot;MuiCollapse-wrapper MuiCollapse-vertical css-hboir5&quot;]/div[@class=&quot;MuiCollapse-wrapperInner MuiCollapse-vertical css-8atqhb&quot;]/div[@class=&quot;MuiAccordion-region&quot;]/div[@class=&quot;MuiAccordionDetails-root css-u7qq7e&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;py-1&quot;]/div[@class=&quot;flex flex-row gap-1 items-center&quot;]/div[@class=&quot;text-xs sm:text-base font-thin w-[100%]&quot;]/p[1]</value>
      <webElementGuid>005c3149-cfc1-4eb2-b311-6e3e82dadca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div/div/div/p</value>
      <webElementGuid>b9130d4c-a0ed-4d10-87cc-71739673517f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Alojamiento'])[1]/following::p[1]</value>
      <webElementGuid>754f4aec-41e3-492c-a1b7-ca2584b62f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filtrar por'])[1]/following::p[1]</value>
      <webElementGuid>2bb8132d-20e8-4d9d-9bfb-6d5459377264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estrellas'])[1]/preceding::p[7]</value>
      <webElementGuid>6c623679-89ac-455c-bd3c-7ad2896b9270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplicar'])[1]/preceding::p[13]</value>
      <webElementGuid>f1e62e3b-2740-4a63-b157-1636fd0d7c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotel']/parent::*</value>
      <webElementGuid>60a58142-8be3-4c45-932d-3ecc289fad39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/div/div/div/div/div/div/div/div/p</value>
      <webElementGuid>9e963537-e2a5-4f70-9a26-fbe5c92641b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Hotel' or . = 'Hotel')]</value>
      <webElementGuid>e0f75ca0-b9e6-42d7-83b2-2e90173aad58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
