<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Recomendado</name>
   <tag></tag>
   <elementGuidId>2b4040f0-2f9e-4783-bae1-8a45795899a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RECOMMENDED-Recomendado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RECOMMENDED-Recomendado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3b94b3b-8d60-4351-945d-1a06b9e91721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RECOMMENDED-Recomendado</value>
      <webElementGuid>83827a3f-d137-4009-8df8-783700fe1cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>muscle-select-option clickable muscle-select-selected-option text-white</value>
      <webElementGuid>3c97d828-adc8-4255-8b90-31955c2452be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ea3b56ac-a515-409f-a4d9-3ad0543535c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recomendado</value>
      <webElementGuid>2004ab7a-fe71-4407-a7c1-0319662d1ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RECOMMENDED-Recomendado&quot;)</value>
      <webElementGuid>4e29b0d8-3529-4d2a-99a7-e0d6b2c7fb00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='RECOMMENDED-Recomendado']</value>
      <webElementGuid>155a3d49-ed9c-4e38-aed0-ee6e3345678a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='muscle-select-options']/div</value>
      <webElementGuid>a5937e30-efc2-405f-9fe7-40cd9855b71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recomendado'])[1]/following::div[5]</value>
      <webElementGuid>9aa9613b-0fbc-4cb0-a0c2-798769fbd7a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordenar por'])[1]/following::div[6]</value>
      <webElementGuid>97e3c657-86e7-4308-b0e4-65a57b72feac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Precio más bajo'])[1]/preceding::div[1]</value>
      <webElementGuid>2b5c7d01-00be-4f90-85a3-990b13073c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Precio más alto'])[1]/preceding::div[2]</value>
      <webElementGuid>7237f4c2-c737-4733-b333-b6de4efa1c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>5d565332-240b-42cf-83b8-ba0ef1fbc73f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'RECOMMENDED-Recomendado' and (text() = 'Recomendado' or . = 'Recomendado')]</value>
      <webElementGuid>6f308e56-aa14-4580-b2b4-33c633cc6e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
