<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>1513a297-8434-4c8e-b2ee-6dc01ed92314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Precio más bajo'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.muscle-select.text-sm.h-fit.clickable > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a3e7c333-10e2-4948-932b-8793de69c0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>d95aaf9e-10c5-4055-ad50-4fe816ef4c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>28a2db83-ef5b-401d-bf9c-9a741a5f7771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>d70283dd-686a-462f-b42c-c0a764604e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>8fddc6c1-287f-46ac-95a3-d41c9a9b0d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>66ad537c-65c9-4358-8358-1d97dcc8cfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#7C7F78</value>
      <webElementGuid>e9be4579-0412-443a-aa29-3579821d6671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;global-page global-responsive-horizontal-paddings&quot;]/div[@class=&quot;flex flex-row gap-8&quot;]/div[@class=&quot;flex-1 flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col gap-4 w-full h-fit&quot;]/div[@class=&quot;flex flex-row justify-between items-center&quot;]/div[@class=&quot;relative flex flex-col outline-none w-fit&quot;]/div[@class=&quot;muscle-select text-sm h-fit clickable&quot;]/svg[1]</value>
      <webElementGuid>aeebcdf3-51d0-48a8-a530-cba0e67acc59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Precio más bajo'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>f316f48c-9fc4-44df-a9b1-dfe9fd376798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordenar por'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>0c4a5e63-c9ca-48d7-a13b-9fb517503e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selina San Jose - Hostel'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>6fcb901a-3050-4699-8c3f-a8c9df3d4b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ave. 9, Calles 13 y 15, San José, 10101'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>0f98b4f2-1a9f-4cfc-af86-0ecf9a98a376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
