<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Per</name>
   <tag></tag>
   <elementGuidId>a4049a44-5a81-420f-ac2e-f8a7406fb084</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PE-Perú</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PE-Perú']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ff1c331-ed3f-4ccd-bbbf-affcbcfac731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PE-Perú</value>
      <webElementGuid>07f5f8a0-4f66-484f-8a9f-5470fe6cbbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>muscle-select-option clickable text-black muscle-select-focused-option</value>
      <webElementGuid>5064e851-077a-49b1-9752-c53601088912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c8a5aeeb-b13d-467b-adbb-cec87a5fea2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perú</value>
      <webElementGuid>3f6f0db1-ab4c-4c84-a7e3-eb09bee87e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PE-Perú&quot;)</value>
      <webElementGuid>7d1c93df-111a-4370-99d1-787ae13440a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='PE-Perú']</value>
      <webElementGuid>d9d373cf-3322-4c20-b333-0fc4bc1f0521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='muscle-select-options']/div[178]</value>
      <webElementGuid>e1679ec3-99e4-4ee7-8605-c2cbb2d1bd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Países Bajos'])[1]/following::div[1]</value>
      <webElementGuid>1222fdf6-2aa8-4518-b3dd-4b615cf6c6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paraguay'])[1]/following::div[2]</value>
      <webElementGuid>ca02e4e8-0d16-452c-90c7-ef9c6c32ef03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pitcairn'])[1]/preceding::div[1]</value>
      <webElementGuid>eaa42d1f-4820-4de7-a669-51bf48c0411a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polinesia Francesa'])[1]/preceding::div[2]</value>
      <webElementGuid>826fc91a-3d05-42ea-972c-838bdcd8641c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perú']/parent::*</value>
      <webElementGuid>b689ea07-7f45-4ab1-a127-25abba64c097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[178]</value>
      <webElementGuid>e2bf83f1-4a7a-4d99-94e3-73878190d503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'PE-Perú' and (text() = 'Perú' or . = 'Perú')]</value>
      <webElementGuid>ee259822-0635-4b39-be3b-7d08cf97c9fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
