<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Estado civil CasadDireccin Calle1</name>
   <tag></tag>
   <elementGuidId>681ce4fc-28ce-4c70-aed5-31c06795a0b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div[2]/div[2]/div/div[2]/div[2]/div/div/section[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>ddc61bc3-2d68-459a-94bc-83b8e18706e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full flex flex-col gap-6 md:flex-row md:gap-11</value>
      <webElementGuid>0f51617f-ea88-4090-ba82-f073f8fe83f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Estado civil *Casad@Dirección *Calle1</value>
      <webElementGuid>22855eb3-bd3a-48c5-b6e4-17420d6b4c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;global-page global-responsive-horizontal-paddings&quot;]/div[@class=&quot;hidden md:flex&quot;]/div[@class=&quot;w-full flex flex-col gap-8&quot;]/div[@class=&quot;w-full flex flex-col gap-4&quot;]/div[@class=&quot;w-full flex flex-col gap-4&quot;]/div[@class=&quot;w-full flex flex-col gap-4 self-center px-0 sm:px-36&quot;]/div[@class=&quot;flex flex-col gap-6 pt-12&quot;]/section[@class=&quot;w-full flex flex-col gap-6 md:flex-row md:gap-11&quot;]</value>
      <webElementGuid>524ec7f8-1fe2-4c74-8c8c-7241e3478f71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div[2]/div/div[2]/div[2]/div/div/section[3]</value>
      <webElementGuid>3ea61e8a-ea80-44ef-80fd-9208d9150918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DD/MM/YYYY'])[1]/following::section[1]</value>
      <webElementGuid>87ce4df1-8c10-45ff-969d-1ae1c1654bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de nacimiento *'])[1]/following::section[1]</value>
      <webElementGuid>61ace54f-de4a-4f62-a30e-c461750e44f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]</value>
      <webElementGuid>3ce706a5-2d6e-4025-89c6-18374288c0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Estado civil *Casad@Dirección *Calle1' or . = 'Estado civil *Casad@Dirección *Calle1')]</value>
      <webElementGuid>53ecc423-4442-4976-b19d-edc36a609824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
