<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Descubre nuestras recomendaciones para _f716b8</name>
   <tag></tag>
   <elementGuidId>ed4194f7-eea2-40bb-bd26-4b82aba2db26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.home-screen-content.global-page.global-responsive-horizontal-paddings</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d449d99d-9587-4c95-9e4a-08d8280213d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-screen-content global-page global-responsive-horizontal-paddings</value>
      <webElementGuid>d26150e5-6bd5-433e-bbfd-890474921be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descubre nuestras recomendaciones para tiPunta CanaBogotáBarilocheCiudad de PanamáCuscoPiuraArequipaMiami</value>
      <webElementGuid>22305319-38f0-4bab-8fef-9fd7b0e4175b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home-screen relative&quot;]/div[@class=&quot;home-screen-content global-page global-responsive-horizontal-paddings&quot;]</value>
      <webElementGuid>81142fcf-680c-4b6c-8acf-1b4a24bb2fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[2]/div[3]</value>
      <webElementGuid>c3b96cbf-0dd7-409e-b538-99efb89a9c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[1]/following::div[6]</value>
      <webElementGuid>81d8813d-9e28-4cc8-98eb-947d04d1b8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listo'])[1]/following::div[27]</value>
      <webElementGuid>11f4ad2e-159c-4de6-94b3-97cdd33fbeaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡Estamos aquí para ayudarte!'])[1]/preceding::div[21]</value>
      <webElementGuid>297aa6c2-fa6b-4f9a-b478-470066fe8175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>8153e30c-b709-4918-ad48-fd0944a21dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Descubre nuestras recomendaciones para tiPunta CanaBogotáBarilocheCiudad de PanamáCuscoPiuraArequipaMiami' or . = 'Descubre nuestras recomendaciones para tiPunta CanaBogotáBarilocheCiudad de PanamáCuscoPiuraArequipaMiami')]</value>
      <webElementGuid>dcb2b136-ede4-4870-9012-dbb7f9546dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
