<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Aeropuerto Intl Jorge Chvez, LIM, Per</name>
   <tag></tag>
   <elementGuidId>523bc2f8-0d6b-4dad-b86e-1436495c2681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pickUpLocation-autocomplete-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pickUpLocation-autocomplete-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8adfb437-56e0-49b5-84df-b9942939f8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option MuiBox-root css-16r7kf5 Mui-focused</value>
      <webElementGuid>3908e0e0-a79c-40fd-9a13-f7f0c6662ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5a0b2629-340e-44fc-830c-7bfb86c1a671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>491b9209-152a-4194-b12c-09d0523d425e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pickUpLocation-autocomplete-option-0</value>
      <webElementGuid>1d7ed760-0061-4f64-ad1d-d0f4854e2911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ec0251a8-f4f4-4ef8-a9a4-15ff0b2e77e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fff96dd8-0bd0-4438-a688-5776ca8b1ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d964b0c-a4bb-4737-886e-50633eda8a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aeropuerto Intl Jorge Chávez, LIM, Perú</value>
      <webElementGuid>e1cfbec0-92f6-4694-a40b-22779790a199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pickUpLocation-autocomplete-option-0&quot;)</value>
      <webElementGuid>d45f7c37-f755-4cdd-8445-2e9ba0fcbc05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='pickUpLocation-autocomplete-option-0']</value>
      <webElementGuid>3b7185d8-3cbc-4c93-bb8e-f79d73118ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pickUpLocation-autocomplete-listbox']/li</value>
      <webElementGuid>a04ff629-6f1f-47ab-bc8b-8ae063f9750a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Métodos de pago:'])[1]/following::li[1]</value>
      <webElementGuid>8689056b-354d-46e7-b013-e37bb9fa9f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Términos y condiciones'])[1]/following::li[1]</value>
      <webElementGuid>171c3dfd-8721-4348-b095-1c44bc7ca87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>cd47735f-83ce-4954-99c6-23ab9102a8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'pickUpLocation-autocomplete-option-0' and (text() = 'Aeropuerto Intl Jorge Chávez, LIM, Perú' or . = 'Aeropuerto Intl Jorge Chávez, LIM, Perú')]</value>
      <webElementGuid>b186334d-6233-44b9-b9f6-c929d661eefc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
