<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Revisa y paga_PrivateSwitchBase-input_e4d2f2</name>
   <tag></tag>
   <elementGuidId>aa7e2931-5d74-4449-a762-be1ae992e435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.PrivateSwitchBase-input.css-1m9pwf3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1e8a69f-c47c-4440-a2fd-02f73e58f0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input css-1m9pwf3</value>
      <webElementGuid>e85069f5-359e-4c37-bbc9-42da0dac94b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5bc2d108-ac20-4165-bf54-db77f470ae60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;global-page global-responsive-horizontal-paddings&quot;]/div[@class=&quot;flex flex-col md:flex-wrap w-full gap-[80px] md:flex-row-reverse&quot;]/div[@class=&quot;flex-[2] w-full md:min-w-[400px] flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col gap-8 w-full&quot;]/div[@class=&quot;flex flex-col gap-8&quot;]/div[@class=&quot;flex flex-col gap-8&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;global-input&quot;]/div[@class=&quot;flex flex-col gap-1 overflow-auto&quot;]/div[@class=&quot;flex
                    flex-row
                    gap-4
                    flex-1
                    items-center
                    border p-2 rounded-lg border-neutral-700&quot;]/div[@class=&quot;h-fit&quot;]/span[@class=&quot;MuiButtonBase-root MuiRadio-root MuiRadio-colorPrimary PrivateSwitchBase-root MuiRadio-root MuiRadio-colorPrimary MuiRadio-root MuiRadio-colorPrimary css-yjtr5y&quot;]/input[@class=&quot;PrivateSwitchBase-input css-1m9pwf3&quot;]</value>
      <webElementGuid>85585400-8df5-4d34-b03a-8a0a17ea8b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='radio']</value>
      <webElementGuid>4a23c8cb-32dc-46c2-8fe2-34518cf8d3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[3]/div[2]/div[2]/div/div[2]/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>8c1d8a8d-e700-4094-acc6-144750a124c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>394a5dd1-e756-451c-b8f5-ee685c1a11d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio']</value>
      <webElementGuid>1b520086-7ebc-43de-9a6f-e5df0d98ac99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
