<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SeleccionarTarjeta</name>
   <tag></tag>
   <elementGuidId>a48d4f7e-116e-45e9-8e1b-569f48d64035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[3]/div[2]/div[2]/div/div[2]/div[2]/div[2]/div[1]/div/div/div[2]/div[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.PrivateSwitchBase-input.css-1m9pwf3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67cc54bd-0715-458b-9ac4-0fe94ad3849a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input css-1m9pwf3</value>
      <webElementGuid>6cf313ce-1c7a-4efb-9d99-4ae4ac0f801a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6148d131-8d45-482f-9c6e-2a576794c9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;global-page global-responsive-horizontal-paddings&quot;]/div[@class=&quot;flex flex-col md:flex-wrap w-full gap-[80px] md:flex-row-reverse&quot;]/div[@class=&quot;flex-[2] w-full md:min-w-[400px] flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col gap-8 w-full&quot;]/div[@class=&quot;flex flex-col gap-8&quot;]/div[@class=&quot;flex flex-col gap-8&quot;]/div[@class=&quot;flex flex-col gap-3&quot;]/div[@class=&quot;global-input&quot;]/div[@class=&quot;flex flex-col gap-1 overflow-auto&quot;]/div[@class=&quot;flex
                    flex-row
                    gap-4
                    flex-1
                    items-center
                    border p-2 rounded-lg border-neutral-700&quot;]/div[@class=&quot;h-fit&quot;]/span[@class=&quot;MuiButtonBase-root MuiRadio-root MuiRadio-colorPrimary PrivateSwitchBase-root MuiRadio-root MuiRadio-colorPrimary MuiRadio-root MuiRadio-colorPrimary css-yjtr5y&quot;]/input[@class=&quot;PrivateSwitchBase-input css-1m9pwf3&quot;]</value>
      <webElementGuid>320c4342-246c-40f8-9a80-919c2d0eb45c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='radio']</value>
      <webElementGuid>bf05fd88-655f-4c9e-a922-530b6c8e583c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div[3]/div[2]/div[2]/div/div[2]/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>58d0bed4-dcad-4c3b-80da-4b0088132307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f164e6ce-689b-45cc-a4ed-6a6b236193fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio']</value>
      <webElementGuid>f37ce3a3-70e4-4777-bf8c-dc7aac7dda2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
